export class BasicDetails {
    basicLpsId!: number;
    clientName!: String;
    userName!: String;
    projectName!: String;
    pmcName!: String;
    consultantName!: String;
    contractorName!: String;
    dealerContractorName!: String;
    address!: String;
    location!: String;
    industryType!: String;
    soilResistivity!: String;
    viewerName!: String;
    // company!: String;
    // designation!: String;
    contactNumber!: String;
    mailId!: String;
    fileName!: String;
    fileSize!: String;
    fileId!: Number;
    availabilityOfPreviousReport!: String;
    allStepsCompleted!: String;
	createdDate!: Date;
    createdBy!: String;
	updatedDate!: Date;
    updatedBy!: String;
    status!: String;
    inspectorEmail!: String;
    inspectorName!: String;
    data!:FormData;
}